DROP DATABASE IF EXISTS krautundrueben;
CREATE DATABASE IF NOT EXISTS krautundrueben;
USE krautundrueben;

CREATE TABLE KUNDE (
    KUNDENNR        INTEGER NOT NULL,
    NACHNAME        VARCHAR(50),
    VORNAME         VARCHAR(50),
    GEBURTSDATUM	DATE,
	STRASSE         VARCHAR(50),
	HAUSNR			VARCHAR(6),			
    PLZ             VARCHAR(5),
    ORT             VARCHAR(50),
    TELEFON         VARCHAR(25),
    EMAIL           VARCHAR(50),
    PRIMARY KEY (KUNDENNR)
);

CREATE TABLE LIEFERANT (
    LIEFERANTENNR   INTEGER NOT NULL,
    LIEFERANTENNAME VARCHAR(50),
    STRASSE         VARCHAR(50),
    HAUSNR			VARCHAR(6),
    PLZ             VARCHAR(5),
    ORT             VARCHAR(50),
    TELEFON			VARCHAR(25),
    EMAIL           VARCHAR(50),
    PRIMARY KEY (LIEFERANTENNR)
);

CREATE TABLE ZUTAT(
    ZUTATENNR			INTEGER NOT NULL,
    BEZEICHNUNG         VARCHAR(50),
    EINHEIT        		VARCHAR (25),
    NETTOPREIS       	DECIMAL(10,2),
    BESTAND             INTEGER,
    LIEFERANT			INTEGER,
	KALORIEN			INTEGER,
	KOHLENHYDRATE		DECIMAL (10,2),
	PROTEIN			    DECIMAL(10,2),
	PRIMARY KEY (ZUTATENNR),
	FOREIGN KEY (LIEFERANT) REFERENCES LIEFERANT (LIEFERANTENNR)
);


CREATE TABLE BESTELLUNG (
    BESTELLNR        INTEGER AUTO_INCREMENT NOT NULL,
    KUNDENNR         INTEGER,
    BESTELLDATUM     DATE,
    RECHNUNGSBETRAG  DECIMAL(10,2),
    PRIMARY KEY (BESTELLNR),
    FOREIGN KEY (KUNDENNR) REFERENCES KUNDE (KUNDENNR)
);

CREATE TABLE BESTELLUNGZUTAT (
    BESTELLNR       INTEGER NOT NULL,
    ZUTATENNR       INTEGER,
    MENGE     		INTEGER,
    PRIMARY KEY (BESTELLNR,ZUTATENNR),
    FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG (BESTELLNR),
    FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR)
);


CREATE TABLE REZEPT (
    REZEPTNR        INTEGER AUTO_INCREMENT NOT NULL,
    NAME         	VARCHAR (125),
    ZUBEREITUNG     VARCHAR (1250),
    PRIMARY KEY (REZEPTNR)
);

CREATE TABLE BESTELLUNGREZEPT (
    BESTELLNR       INTEGER NOT NULL,
    REZEPTNR        INTEGER,
    MENGE     		INTEGER,
    PRIMARY KEY (BESTELLNR,REZEPTNR),
    FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG (BESTELLNR),
    FOREIGN KEY (REZEPTNR ) REFERENCES REZEPT (REZEPTNR)
);

CREATE TABLE REZEPTZUTAT (
	ZUTATENNR       INTEGER NOT NULL,
    REZEPTNR        INTEGER,
    MENGE     		INTEGER,
    PRIMARY KEY (ZUTATENNR,REZEPTNR),
    FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR),
    FOREIGN KEY (REZEPTNR ) REFERENCES REZEPT (REZEPTNR)
);

CREATE TABLE KATEGORIE (
    KATEGNR			INTEGER,
    KATEGNAME  		VARCHAR(20),
    PRIMARY KEY (KATEGNR)
);

CREATE TABLE ALLERGENE (
	ALLERGNR			INTEGER,
    ALLERGNAME 			VARCHAR(20),
    PRIMARY KEY (ALLERGNR)
);

CREATE TABLE REZEPTKATEGORIE (
	REZEPTNR 	INTEGER,
	KATEGNR 	INTEGER,
	PRIMARY KEY (REZEPTNR,KATEGNR),
    FOREIGN KEY (REZEPTNR) REFERENCES REZEPT (REZEPTNR),
    FOREIGN KEY (KATEGNR ) REFERENCES KATEGORIE (KATEGNR)
);
