DROP DATABASE IF EXISTS krautundrueben;
CREATE DATABASE IF NOT EXISTS krautundrueben;
USE krautundrueben;

CREATE TABLE KUNDE (
    KUNDENR        INTEGER NOT NULL AUTO_INCREMENT,
    NACHNAME        VARCHAR(50),
    VORNAME         VARCHAR(50),
    GEBURTSDATUM    DATE,
    STRASSE         VARCHAR(50),
    HAUSNR          VARCHAR(6),
    PLZ             VARCHAR(5),
    ORT             VARCHAR(50),
    TELEFON         VARCHAR(25),
    EMAIL           VARCHAR(50),
    PRIMARY KEY (KUNDENR)
);

CREATE TABLE LIEFERANT (
    LIEFERANTNR   INTEGER NOT NULL,
    LIEFERANT_NAME VARCHAR(50),
    STRASSE         VARCHAR(50),
    HAUSNR          VARCHAR(6),
    PLZ             VARCHAR(5),
    ORT             VARCHAR(50),
    TELEFON         VARCHAR(25),
    EMAIL           VARCHAR(50),
    PRIMARY KEY (LIEFERANTNR)
);

CREATE TABLE ZUTAT (
    ZUTATNR       INTEGER NOT NULL,
    ZUTAT_NAME     VARCHAR(50),
    EINHEIT         VARCHAR (25),
    NETTOPREIS      DECIMAL(10,2),
    BESTAND         INTEGER,
    LIEFERANTNR       INTEGER,
    KALORIEN        INTEGER,
    KOHLENHYDRATE   DECIMAL (10,2),
    PROTEIN         DECIMAL(10,2),
    PRIMARY KEY (ZUTATNR),
    FOREIGN KEY (LIEFERANTNR) REFERENCES LIEFERANT (LIEFERANTNR)
);

CREATE TABLE REZEPT (
    REZEPTNR        INTEGER AUTO_INCREMENT NOT NULL,
    REZEPT_NAME            VARCHAR(100),
    ZUBEREITUNG     VARCHAR(1500),
    PRIMARY KEY (REZEPTNR)
);

CREATE TABLE REZEPTZUTAT (
    REZEPTNR        INTEGER,
    ZUTATNR       INTEGER,
    MENGE           INTEGER,
    PRIMARY KEY (REZEPTNR, ZUTATNR),
    FOREIGN KEY (REZEPTNR) REFERENCES REZEPT (REZEPTNR),
    FOREIGN KEY (ZUTATNR) REFERENCES ZUTAT (ZUTATNR)
);

CREATE TABLE ERNAEHRUNGSKATEGORIE (
    KATEGORIENR     INTEGER,
    KATEGORIE_NAME  VARCHAR(50),
    PRIMARY KEY (KATEGORIENR)
);

CREATE TABLE REZEPTERNAEHRUNGSKATEGORIE (
    REZEPTNR        INTEGER,
    KATEGORIENR     INTEGER,
    PRIMARY KEY (REZEPTNR, KATEGORIENR),
    FOREIGN KEY (REZEPTNR) REFERENCES REZEPT (REZEPTNR),
    FOREIGN KEY (KATEGORIENR) REFERENCES ERNAEHRUNGSKATEGORIE (KATEGORIENR)
);

CREATE TABLE ALLERGENE (
    ALLERGENNR        INTEGER,
    ALLERGEN_NAME   VARCHAR(50),
    PRIMARY KEY (ALLERGENNR)
);

CREATE TABLE ZUTATENALLERGENE (
    ZUTATNR       INTEGER,
    ALLERGENNR        INTEGER,
    PRIMARY KEY (ZUTATNR, ALLERGENNR),
    FOREIGN KEY (ZUTATNR) REFERENCES ZUTAT (ZUTATNR),
    FOREIGN KEY (ALLERGENNR) REFERENCES ALLERGENE (ALLERGENNR)
);

CREATE TABLE BESTELLUNG (
    BESTELLUNGNR       INTEGER AUTO_INCREMENT NOT NULL,
    KUNDENR        INTEGER,
    BESTELLDATUM    DATE,
    RECHNUNGSBETRAG DECIMAL(10,2),
    PRIMARY KEY (BESTELLUNGNR),
    FOREIGN KEY (KUNDENR) REFERENCES KUNDE (KUNDENR)
);

CREATE TABLE BESTELLUNGREZEPT (
    BESTELLUNGNR       INTEGER NOT NULL,
    REZEPTNR       	INTEGER,
    MENGE           INTEGER,
    PRIMARY KEY (BESTELLUNGNR, REZEPTNR),
    FOREIGN KEY (BESTELLUNGNR) REFERENCES BESTELLUNG (BESTELLUNGNR),
    FOREIGN KEY (REZEPTNR)  REFERENCES REZEPT (REZEPTNR)
);

CREATE TABLE BESTELLUNGZUTATEN (
    BESTELLUNGNR       INTEGER NOT NULL,
    ZUTATNR       INTEGER,
    MENGE           INTEGER,
    PRIMARY KEY (BESTELLUNGNR, ZUTATNR),
    FOREIGN KEY (BESTELLUNGNR) REFERENCES BESTELLUNG (BESTELLUNGNR),
    FOREIGN KEY (ZUTATNR) REFERENCES ZUTAT (ZUTATNR)
);