-- Auswahl aller Rezepte, die weniger als fünf Zutaten enthalten und eine bestimmte Ernährungskategorie erfüllen


SELECT r.REZEPTNR, r.REZEPT_NAME, COUNT(rz.ZUTATNR), e.KATEGORIE_NAME 
FROM REZEPT r 
INNER JOIN REZEPTZUTAT rz
ON r.REZEPTNR =rz.REZEPTNR 
INNER JOIN ZUTAT z 
ON z.ZUTATNR = rz.ZUTATNR 
INNER JOIN REZEPTERNAEHRUNGSKATEGORIE re
ON r.REZEPTNR = re.REZEPTNR 
INNER JOIN ERNAEHRUNGSKATEGORIE e 
ON e.KATEGORIENR  = re.KATEGORIENR 
GROUP BY r.REZEPTNR, r.REZEPT_NAME, e.KATEGORIE_NAME 
HAVING COUNT(rz.ZUTATNR) <= 5 AND KATEGORIE_NAME = 'Salate';