-- Auswahl aller Rezepte einer bestimmten Ernährungskategorie

SELECT r.REZEPT_NAME, e.KATEGORIE_NAME 
FROM REZEPT  r 
RIGHT JOIN REZEPTERNAEHRUNGSKATEGORIE re
ON r.REZEPTNR = re.REZEPTNR 
INNER JOIN ERNAEHRUNGSKATEGORIE e 
ON re.KATEGORIENR = e.KATEGORIENR 
WHERE e.KATEGORIE_NAME = 'Salate'

