-- Insert the recipe into the REZEPT table
INSERT INTO REZEPT (REZEPT_NAME, ZUBEREITUNG) 
VALUES ('Spaghetti Carbonara', 'Cook spaghetti, fry bacon, mix with beaten eggs and Parmesan cheese.');

-- Retrieve the recipe number (REZEPTNR) generated by the AUTO_INCREMENT
SET @recipe_id = LAST_INSERT_ID();

-- Insert the ingredients into the REZEPTZUTAT table
-- Eggs
INSERT IGNORE INTO REZEPTZUTAT (REZEPTNR, ZUTATNR, MENGE)
VALUES (@recipe_id, (SELECT ZUTATNR FROM ZUTAT WHERE ZUTAT_NAME = 'Ei'), 2);

-- Spaghetti
INSERT IGNORE INTO REZEPTZUTAT (REZEPTNR, ZUTATNR, MENGE)
VALUES (@recipe_id, (SELECT ZUTATNR FROM ZUTAT WHERE ZUTAT_NAME = 'Spaghetti'), 200);

-- Bacon
INSERT IGNORE INTO REZEPTZUTAT (REZEPTNR, ZUTATNR, MENGE)
VALUES (@recipe_id, (SELECT ZUTATNR FROM ZUTAT WHERE ZUTAT_NAME = 'Schweinefleisch'), 150);

-- Parmesan cheese
INSERT IGNORE INTO REZEPTZUTAT (REZEPTNR, ZUTATNR, MENGE)
VALUES (@recipe_id, (SELECT ZUTATNR FROM ZUTAT WHERE ZUTAT_NAME = 'Parmesan'), 50);