CREATE PROCEDURE krautundrueben.RezeptMitKategorieUndAnzahlZutat(
	IN categoryName VARCHAR(100),
	IN maxZutat INT
)
BEGIN
	SELECT r.REZEPTNR, r.REZEPT_NAME, e.KATEGORIE_NAME, COUNT(rz.ZUTATNR) 
    FROM REZEPT r 
    INNER JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR 
    INNER JOIN ZUTAT z ON z.ZUTATNR = rz.ZUTATNR 
    INNER JOIN REZEPTERNAEHRUNGSKATEGORIE re ON r.REZEPTNR = re.REZEPTNR 
    INNER JOIN ERNAEHRUNGSKATEGORIE e ON e.KATEGORIENR  = re.KATEGORIENR
    WHERE e.KATEGORIE_NAME = categoryName
    GROUP BY r.REZEPTNR, e.KATEGORIE_NAME
    HAVING COUNT(rz.ZUTATNR) <= maxZutat; 
	
END 