SELECT ORT, ZUTAT_NAME, SUM(ordered_amount), EINHEIT
	FROM 
(
SELECT
		k.ORT, z.ZUTAT_NAME, bz.MENGE as ordered_amount, z.EINHEIT
	FROM
		KUNDE k
	JOIN BESTELLUNG b ON
		b.KUNDENR = k.KUNDENR
	JOIN BESTELLUNGZUTATEN bz ON
		bz.BESTELLUNGNR = b.BESTELLUNGNR
	JOIN ZUTAT z on
		bz.ZUTATNR = z.ZUTATNR
UNION
	SELECT k.ORT, z.ZUTAT_NAME, (rz.MENGE * br.MENGE) as ordered_amount, z.EINHEIT
	FROM
		KUNDE k
	JOIN BESTELLUNG b ON
		b.KUNDENR = k.KUNDENR
	JOIN BESTELLUNGREZEPT br ON
		br.BESTELLUNGNR = b.BESTELLUNGNR
	JOIN REZEPT r ON
		br.REZEPTNR = r.REZEPTNR
	JOIN REZEPTZUTAT rz ON
		rz.REZEPTNR = r.REZEPTNR
	JOIN ZUTAT z ON
		rz.ZUTATNR = z.ZUTATNR 
		
) as agg_table
GROUP BY ORT, ZUTAT_NAME, EINHEIT
ORDER BY ORT
